# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("登录")
        Form.resize(450, 377)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 100, 81, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(110, 180, 81, 51))
        self.label_2.setObjectName("label_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(Form)
        self.usernameLineEdit.setGeometry(QtCore.QRect(150, 100, 141, 41))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(Form)
        self.passwordLineEdit.setGeometry(QtCore.QRect(150, 180, 141, 41))
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginPushButton = QtWidgets.QPushButton(Form)
        self.loginPushButton.setGeometry(QtCore.QRect(80, 290, 91, 41))
        self.loginPushButton.setObjectName("loginPushButton")
        self.registerPushButton = QtWidgets.QPushButton(Form)
        self.registerPushButton.setGeometry(QtCore.QRect(230, 290, 91, 41))
        self.registerPushButton.setObjectName("registerPushButton")
        self.tipsLabel = QtWidgets.QLabel(Form)
        self.tipsLabel.setGeometry(QtCore.QRect(110, 240, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tipsLabel.setFont(font)
        self.tipsLabel.setText("")
        self.tipsLabel.setObjectName("tipsLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "账号："))
        self.label_2.setText(_translate("Form", "密码："))
        self.loginPushButton.setText(_translate("Form", "登 录"))
        self.registerPushButton.setText(_translate("Form", "注 册"))
