# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\my_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mbox(object):
    def setupUi(self, Mbox):
        Mbox.setObjectName("Mbox")
        Mbox.resize(283, 443)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../../../收藏夹/iCloud Photos/Downloads/2019/IMG_0574.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Mbox.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Mbox)
        self.label.setGeometry(QtCore.QRect(5, 51, 61, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Mbox)
        self.label_2.setGeometry(QtCore.QRect(5, 87, 61, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Mbox)
        self.label_4.setGeometry(QtCore.QRect(5, 120, 61, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.usernameEdit = QtWidgets.QLineEdit(Mbox)
        self.usernameEdit.setGeometry(QtCore.QRect(75, 51, 146, 21))
        self.usernameEdit.setReadOnly(False)
        self.usernameEdit.setClearButtonEnabled(True)
        self.usernameEdit.setObjectName("usernameEdit")
        self.okButton = QtWidgets.QPushButton(Mbox)
        self.okButton.setGeometry(QtCore.QRect(30, 390, 71, 28))
        self.okButton.setObjectName("okButton")
        self.label_5 = QtWidgets.QLabel(Mbox)
        self.label_5.setGeometry(QtCore.QRect(5, 160, 60, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.passwordEdit = QtWidgets.QLineEdit(Mbox)
        self.passwordEdit.setGeometry(QtCore.QRect(75, 87, 146, 21))
        self.passwordEdit.setClearButtonEnabled(True)
        self.passwordEdit.setObjectName("passwordEdit")
        self.universityEdit = QtWidgets.QLineEdit(Mbox)
        self.universityEdit.setGeometry(QtCore.QRect(75, 160, 146, 21))
        self.universityEdit.setClearButtonEnabled(True)
        self.universityEdit.setObjectName("universityEdit")
        self.cancelButton = QtWidgets.QPushButton(Mbox)
        self.cancelButton.setGeometry(QtCore.QRect(140, 390, 71, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.nameEdit = QtWidgets.QLineEdit(Mbox)
        self.nameEdit.setGeometry(QtCore.QRect(75, 120, 146, 21))
        self.nameEdit.setClearButtonEnabled(True)
        self.nameEdit.setObjectName("nameEdit")
        self.msg = QtWidgets.QLabel(Mbox)
        self.msg.setGeometry(QtCore.QRect(30, 10, 201, 16))
        self.msg.setObjectName("msg")
        self.label_3 = QtWidgets.QLabel(Mbox)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 54, 12))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(Mbox)
        self.textEdit.setGeometry(QtCore.QRect(70, 200, 151, 141))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Mbox)
        QtCore.QMetaObject.connectSlotsByName(Mbox)

    def retranslateUi(self, Mbox):
        _translate = QtCore.QCoreApplication.translate
        Mbox.setWindowTitle(_translate("Mbox", "账号"))
        self.label.setText(_translate("Mbox", "账号"))
        self.label_2.setText(_translate("Mbox", "密码"))
        self.label_4.setText(_translate("Mbox", "姓名"))
        self.okButton.setText(_translate("Mbox", "确定"))
        self.label_5.setText(_translate("Mbox", "大学"))
        self.cancelButton.setText(_translate("Mbox", "取消"))
        self.msg.setText(_translate("Mbox", "提示信息"))
        self.label_3.setText(_translate("Mbox", "个人简介"))
